config/routes.rb
Gonadsmailer::Application.routes.draw do
  get "welcome/index"
  root 'welcome#index'

  post '/send_email' => 'welcome#send_email'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def send_email
    
    from = params[:email][:from]
    to = params[:email][:to]
    subject = params[:email][:subject]
    message = params[:email][:message]

    mail = Gmailer.create_email to, from, subject, message

    if mail.deliver 
      flash[:notice] = "Email sent"
    else
       flash[:notice] = "Email didn't go anywhere"
    end

    redirect_to '/'

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gonadsmailer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Gonadmailer</h1>
<p><%= flash[:notice] if flash[:notice] %></p>

<%= form_for :email, url: send_email_path do |form| %>

  
  <%= form.label :from, "Email From:" %>
  <%= form.text_field :from, value: "whocares@email.com" %>

  <%= form.label :to, "Email To:" %>
  <%= form.text_field :to , value: "dwkns@me.com" %>

  <%= form.label :subject, "Subject" %>
  <%= form.text_field :subject , value: "nadia hatees spulling mitooks" %>

  <%= form.label :message, "Message" %>
  <%= form.text_area :message , value: "Here is the message"%>

  <%= form.submit "Send Email" %>

<% end %>